MagicVilla_Web/Models/ViewModel/NumeroVillaViewModel.cs
using MagicVilla_Web.Models.Dto;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MagicVilla_Web.Models.ViewModel
{
    public class NumeroVillaViewModel
    {
        public NumeroVillaViewModel()
        {
            NumeroVilla = new NumeroVillaCreateDto();
        }

        public NumeroVillaCreateDto NumeroVilla { get; set; }   

        public IEnumerable <SelectListItem>  VillaList { get; set; }    


    }
}

MagicVilla_Web/Controllers/NumeroVillaController.cs
using AutoMapper;
using MagicVilla_API.Modelos;
using MagicVilla_Utilidad;
using MagicVilla_Web.Models.Dto;
using MagicVilla_Web.Models.ViewModel;
using MagicVilla_Web.Services;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Data;

namespace MagicVilla_Web.Controllers
{
    public class NumeroVillaController : Controller
    {

        private readonly INumeroVillaService _numerovillaService;
        private readonly IMapper _mapper;
        private readonly IVillaService _villaService;

        public NumeroVillaController(INumeroVillaService numerovillaService, IVillaService villaService, IMapper mapper)
        {
            _numerovillaService = numerovillaService;
            _villaService = villaService;
            _mapper = mapper;
        }


        [Authorize(Roles = "admin")]
        public async Task <IActionResult> IndexnumeroVilla()
        {
            List<NumeroVillaDto> numerovillaList = new();

            var response = await _numerovillaService.ObtenerTodos<APIResponse>(HttpContext.Session.GetString(DS.SessionToken));

            if (response != null && response.IsExitoso)
            {
                numerovillaList = JsonConvert.DeserializeObject<List<NumeroVillaDto>>(Convert.ToString(response.Resultado));
            }

            return View(numerovillaList);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CrearNumeroVilla()
        {
            NumeroVillaViewModel numeroVillaVM = new();

            var response = await _villaService.ObtenerTodos<APIResponse>(HttpContext.Session.GetString(DS.SessionToken));

            if (response != null && response.IsExitoso)
            {
                numeroVillaVM.VillaList = JsonConvert.DeserializeObject<List<VillaDto>>(Convert.ToString(response.Resultado))
                                          .Select(v => new SelectListItem
                                          {
                                              Text = v.Nombre,
                                              Value = v.Id.ToString()
                                          });
            }

            return View(numeroVillaVM);
        }


        //MetodoPost para hacer la operacion
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CrearNumeroVilla(NumeroVillaViewModel modelo)
        {
            if (ModelState.IsValid)
            {
                var response = await _numerovillaService.Crear<APIResponse>(modelo.NumeroVilla, HttpContext.Session.GetString(DS.SessionToken));
                if (response != null && response.IsExitoso)
                {
                    return RedirectToAction(nameof(IndexnumeroVilla));
                }
                else
                {
                    if (response.ErrorMessages.Count>0)
                    {
                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                    }
                }
            }

            var res = await _villaService.ObtenerTodos<APIResponse>(HttpContext.Session.GetString(DS.SessionToken));

            if (res != null && res.IsExitoso)
            {
                modelo.VillaList = JsonConvert.DeserializeObject<List<VillaDto>>(Convert.ToString(res.Resultado))
                                          .Select(v => new SelectListItem
                                          {
                                              Text = v.Nombre,
                                              Value = v.Id.ToString()
                                          });
            }
            return View(modelo);
        }

        //deeb se exacto el parametro que tengo en el viws de numero vila villaNo
        //metodo get llamada
        [Authorize(Roles = "admin")]
        public async Task <IActionResult> ActualizarNumeroVilla(int villaNo)
        {
            NumeroVillaUpdateViewModel numeroVillaVM = new();

            var response = await _numerovillaService.Obtener<APIResponse>(villaNo, HttpContext.Session.GetString(DS.SessionToken));

            if (response  != null && response.IsExitoso)
            {
                NumeroVillaDto modelo = JsonConvert.DeserializeObject<NumeroVillaDto>(Convert.ToString(response.Resultado));
                numeroVillaVM.NumeroVilla = _mapper.Map<NumeroVillaUpdateDto>(modelo);
            }

            response = await _villaService.ObtenerTodos<APIResponse>(HttpContext.Session.GetString(DS.SessionToken));

            if (response != null && response.IsExitoso)
            {
                numeroVillaVM.VillaList = JsonConvert.DeserializeObject<List<VillaDto>>(Convert.ToString(response.Resultado))
                                          .Select(v => new SelectListItem
                                          {
                                              Text = v.Nombre,
                                              Value = v.Id.ToString()
                                          });
                return View(numeroVillaVM);
            }

            return NotFound();

        }

        //este realiza la operacion de actualizar
        [HttpPost]
        public async Task<IActionResult> ActualizarNumeroVilla(NumeroVillaUpdateViewModel modelo)
        {
            if (ModelState.IsValid)
            {
                var response = await _numerovillaService.Actualizar<APIResponse>(modelo.NumeroVilla, HttpContext.Session.GetString(DS.SessionToken));
                if (response != null && response.IsExitoso)
                {
                    return RedirectToAction(nameof(IndexnumeroVilla));
                }
                else
                {
                    if (response.ErrorMessages.Count > 0)
                    {
                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                    }
                }
            }

            var res = await _villaService.ObtenerTodos<APIResponse>(HttpContext.Session.GetString(DS.SessionToken));

            if (res != null && res.IsExitoso)
            {
                modelo.VillaList = JsonConvert.DeserializeObject<List<VillaDto>>(Convert.ToString(res.Resultado))
                                          .Select(v => new SelectListItem
                                          {
                                              Text = v.Nombre,
                                              Value = v.Id.ToString()
                                          });
            }
            return View(modelo);
        }



        //metodo get llamada
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> RemoverNumeroVilla(int villaNo)
        {
            NumeroVillaDeleteViewModel numeroVillaVM = new();

            var response = await _numerovillaService.Obtener<APIResponse>(villaNo, HttpContext.Session.GetString(DS.SessionToken));

            if (response != null && response.IsExitoso)
            {
                NumeroVillaDto modelo = JsonConvert.DeserializeObject<NumeroVillaDto>(Convert.ToString(response.Resultado));
                numeroVillaVM.NumeroVilla = modelo;
            }

            response = await _villaService.ObtenerTodos<APIResponse>(HttpContext.Session.GetString(DS.SessionToken));

            if (response != null && response.IsExitoso)
            {
                numeroVillaVM.VillaList = JsonConvert.DeserializeObject<List<VillaDto>>(Convert.ToString(response.Resultado))
                                          .Select(v => new SelectListItem
                                          {
                                              Text = v.Nombre,
                                              Value = v.Id.ToString()
                                          });
                return View(numeroVillaVM);
            }

            return NotFound();

        }

        //este realiza la operacion
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoverNumeroVilla(NumeroVillaDeleteViewModel modelo)
        {
            var response = await _numerovillaService.Remover<APIResponse>(modelo.NumeroVilla.VillaNo, HttpContext.Session.GetString(DS.SessionToken));
            if (response != null && response.IsExitoso)
            {
                return RedirectToAction(nameof(IndexnumeroVilla));
            }
            return View(modelo);
        }

    }
}

MagicVilla_Web/Views/NumeroVilla/ActualizarNumeroVilla.cshtml
@model MagicVilla_Web.Models.ViewModel.NumeroVillaUpdateViewModel


@{
    ViewData["Title"] = "UpdateNumeroVilla";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" asp-action="ActualizarNumeroVilla">
    <div class="container border p-3">

        <div asp-validation-summary="All" class="text-danger"></div>
        <input asp-for ="NumeroVilla.VillaNo" hidden/> 


        <div class="row">
            <h2 class="text-info">Actualizar Numero de Villa</h2>
        </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Numero de Villa</label>
                <input asp-for="NumeroVilla.VillaNo" disabled class="form-control" />
                <span asp-validation-for="NumeroVilla.VillaNo" class="text-danger"></span>
            </div>
        </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Villa</label>
                <select asp-for="NumeroVilla.VillaId" class="form-select" asp-items="@Model.VillaList">
                    <option value="">-- Seleccione una Villa --</option>
                </select>
                <span asp-validation-for="NumeroVilla.VillaId" class="text-danger"></span>
            </div>
        </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Detalle Especial</label>
                <textarea asp-for="NumeroVilla.DetalleEspecial" class="form-control"></textarea>
                <span asp-validation-for="NumeroVilla.DetalleEspecial" class="text-danger"></span>

            </div>
        </div>

        <div class="d-grid gap-2 d-md-block mt-2">
            <button type="submit" class="btn btn-primary">Actualizar</button>
            <a asp-controller="NumeroVilla" asp-action="IndexNumeroVilla" class="btn btn-success">Regresar</a>
        </div>


    </div>

</form>

MagicVilla_Web/Views/NumeroVilla/CrearNumeroVilla.cshtml
@model MagicVilla_Web.Models.ViewModel.NumeroVillaViewModel


@{
    ViewData["Title"] = "CrearNumeroVilla";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" asp-action ="CrearNumeroVilla">
    <div class ="container border p-3">

        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="row">
            <h2 class="text-info">Crear Numero de Villa</h2>
     </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Numero de Villa</label>
                <input asp-for="NumeroVilla.VillaNo" class="form-control" />
                <span asp-validation-for="NumeroVilla.VillaNo" class="text-danger"></span>
            </div>
        </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Villa</label>
                <select asp-for="NumeroVilla.VillaId" class="form-select" asp-items="@Model.VillaList">
                    <option value="">-- Seleccione una Villa --</option>
                </select>
                <span asp-validation-for="NumeroVilla.VillaId" class="text-danger"></span>
            </div>
        </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Detalle Especial</label>
                <textarea asp-for="NumeroVilla.DetalleEspecial" class="form-control"></textarea>
                <span asp-validation-for="NumeroVilla.DetalleEspecial" class="text-danger"></span>

            </div>
        </div>

        <div class="d-grid gap-2 d-md-block mt-2">
            <button type="submit" class="btn btn-primary">Grabar</button>
            <a asp-controller="NumeroVilla" asp-action="IndexNumeroVilla" class="btn btn-success">Regresar</a>
        </div>


     </div>

</form>

MagicVilla_Web/Views/NumeroVilla/IndexnumeroVilla.cshtml
@model IEnumerable<MagicVilla_Web.Models.Dto.NumeroVillaDto>
@{
    ViewData["Title"] = "IndexNumeroVilla";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col">

            <h1 class="text-primary">Lista de Numero De Villas</h1>

        </div>
        <div class="col text-end pt-1">
            <a asp-controller="NumeroVilla" asp-action="CrearNumeroVilla" class="btn btn-outline-primary"><i class="bi bi-plus-circle-fill"></i>Crear Nuevo Numero de Villa</a>
        </div>

    </div>


    <table class="table">
        <thead>
            <tr>
                <th>Nombre de la villa</th>
                <th>Numero de Villa</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Villa.Nombre</td>
                    <td>@item.VillaNo</td>
                    <td>
                        <a asp-controller="NumeroVilla" asp-action="ActualizarNumeroVilla" asp-route-villaNo="@item.VillaNo" class="btn btn-success"><i class="bi bi-pencil-square"></i> </a>
                        <a asp-controller="NumeroVilla" asp-action="RemoverNumeroVilla" asp-route-villaNo="@item.VillaNo" class="btn btn-danger"><i class="bi bi-trash3-fill"></i> </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>


</div>

MagicVilla_Web/Views/NumeroVilla/RemoverNumeroVilla.cshtml
@model MagicVilla_Web.Models.ViewModel.NumeroVillaDeleteViewModel


@{
    ViewData["Title"] = "RemoverNumeroVilla";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" asp-action="RemoverNumeroVilla">
    <div class="container border p-3">

        <div asp-validation-summary="All" class="text-danger"></div>
        <input asp-for="NumeroVilla.VillaNo" hidden />


        <div class="row">
            <h2 class="text-info">Remover Numero de Villa</h2>
        </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Numero de Villa</label>
                <input asp-for="NumeroVilla.VillaNo" disabled class="form-control" />
                <span asp-validation-for="NumeroVilla.VillaNo" class="text-danger"></span>
            </div>
        </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Villa</label>
                <select asp-for="NumeroVilla.VillaId" disabled class="form-select" asp-items="@Model.VillaList">
                    <option value="">-- Seleccione una Villa --</option>
                </select>
                <span asp-validation-for="NumeroVilla.VillaId" class="text-danger"></span>
            </div>
        </div>

        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Detalle Especial</label>
                <textarea asp-for="NumeroVilla.DetalleEspecial" disabled class="form-control"></textarea>
                <span asp-validation-for="NumeroVilla.DetalleEspecial" class="text-danger"></span>

            </div>
        </div>

        <div class="d-grid gap-2 d-md-block mt-2">
            <button type="submit" class="btn btn-danger">Remover</button>
            <a asp-controller="NumeroVilla" asp-action="IndexNumeroVilla" class="btn btn-success">Regresar</a>
        </div>


    </div>

</form>